/*
 * Automatically generated by libJConfig-4.0-alpha0 @ rs2[fddccd3]
 * Generated From: ourSpi.jc4 (/home/rs01/RS2/Versuch1/ourSpi.jc4)
 * Generated at Tue May 16 14:11:25 CEST 2023
 * jConfig Built on Tue Nov 26 09:26:22 CET 2019, Build Hash E3AA1574
 *
 * All Parameters declared in peripherals and modules of this subsystem
 */


#pragma once

#define SB_SPARTANMC_BRKPT_TRAP                           	1
#define SB_SPARTANMC_CLOCK_GATING                         	0
#define SB_SPARTANMC_CODEMEM_CAN_STALL                    	0
#define SB_SPARTANMC_CODEMEM_CONNECTED                    	1
#define SB_SPARTANMC_COUNT_BREAKPOINTS                    	4
#define SB_SPARTANMC_COUNT_CYCLECOUNTERS                  	1
#define SB_SPARTANMC_COUNT_EVENTCOUNTERS                  	2
#define SB_SPARTANMC_COUNT_WATCHPOINTS                    	4
#define SB_SPARTANMC_DATAMEM_CAN_STALL                    	0
#define SB_SPARTANMC_DATAMEM_CONNECTED                    	1
#define SB_SPARTANMC_FORWARDING_CAN_STALL                 	0
#define SB_SPARTANMC_FREQUENCY                            	60000000
#define SB_SPARTANMC_HARDWARE_DEBUGGING                   	0
#define SB_SPARTANMC_HARDWARE_MUL                         	1
#define SB_SPARTANMC_IGNORE_UNCONNECTED                   	0
#define SB_SPARTANMC_INTR_VECTOR                          	0x0
#define SB_SPARTANMC_IO_BASE_ADR                          	0x1fc00
#define SB_SPARTANMC_IO_PREFIX                            	0x7f
#define SB_SPARTANMC_PERFORMANCE_COUNTER                  	0
#define SB_SPARTANMC_RESET_VECTOR                         	0x0
#define SB_SPARTANMC_SHOW_INSTR                           	1
#define SB_SPARTANMC_SINGLE_SHIFT                         	0
#define SB_SPARTANMC_SINGLE_STEP_TRAP                     	3
#define SB_SPARTANMC_STOP_SIM_ON_PERI_S9                  	1
#define SB_SPARTANMC_STOP_SIM_ON_X                        	1
#define SB_SPARTANMC_WIDTH_CYCLECOUNTER                   	36
#define SB_SPARTANMC_WIDTH_EVENTCOUNTER                   	36
#define SB_SPARTANMC_WTCHPT_TRAP                          	2
#define SB_PORT_OUT_PORT_WIDTH                            	1
#define SB_PORT_OUT_SUPPORT_TRISTATE                      	1
#define SB_SPARTANMC_MEM_LOCAL_RAMBLOCKS                  	4
#define SB_SPARTANMC_MEM_LOCAL_SHOW_MEM                   	1
#define SB_SPI_MASTER_FREQUENCY_OK                        	1
#define SB_SPI_MASTER_SPI_SS                              	1
#define SB_UART_LIGHT_BAUDRATE                            	115200
#define SB_UART_LIGHT_CLOCK_FREQUENCY                     	60000000
#define SB_UART_LIGHT_ENABLE_TX_CHAIN                     	0
#define SB_UART_LIGHT_FIFO_RX_DEPTH                       	8
#define SB_UART_LIGHT_FIFO_TX_DEPTH                       	8
#define SB_UART_LIGHT_INTERRUPT_SUPPORTED                 	0
#define SB_UART_LIGHT_LOGFILE                             	"spartanmc.txt"
#define SB_UART_LIGHT_LOG_TO_FILE                         	1
#define SB_UART_LIGHT_PRINT_TX                            	1
