/*
 * Automatically generated by libJConfig-4.0-alpha0 @ rs2[fddccd3]
 * Generated From: peripherals_generated_jconfig.c (/home/rs01/RS2/Versuch1/system/subsystems/spartanmc/peripherals_generated_jconfig.c)
 * Generated at Tue May 09 14:18:29 CEST 2023
 * jConfig Built on Tue Nov 26 09:26:22 CET 2019, Build Hash E3AA1574
 *
 * FILE Declarations that can be used to access peripherals
 */

#include <peripherals.h>
#include <stdio.h>

FILE spartanmc_uart_light_file = declare_UART_LIGHT_FILE(&spartanmc_uart_light);
