#
# Automatically generated by libJConfig-4.0-alpha0 @ rs2[fddccd3]
# Generated From: firmwares.mk (/home/rs01/RS2/Versuch1/system/firmwares.mk)
# Generated at Tue May 09 14:13:04 CEST 2023
# jConfig Built on Tue Nov 26 09:26:22 CET 2019, Build Hash E3AA1574
#
# Legacy Make-File, containing configuration for the make part of the toolchain
#

define JCONFIG_FIRMWARE_IDS
spartanmc
endef
export JCONFIG_FIRMWARE_IDS


define JCONFIG_FW_spartanmc_SOURCE
/home/rs01/RS2/Versuch1/firmware
endef
export JCONFIG_FW_spartanmc_SOURCE


define JCONFIG_FW_spartanmc_LINKERSCRIPT
./firmwares/spartanmc.x
endef
export JCONFIG_FW_spartanmc_LINKERSCRIPT


define JCONFIG_FW_spartanmc_SUBSYSTEM
spartanmc
endef
export JCONFIG_FW_spartanmc_SUBSYSTEM


define JCONFIG_FW_spartanmc_LINKLIBS

endef
export JCONFIG_FW_spartanmc_LINKLIBS


