;
; Automatically generated by libJConfig-4.0-alpha0 @ rs2[fddccd3]
; Generated From: ourSpi.jc4 (/home/rs01/RS2/Versuch1/ourSpi.jc4)
; Generated at Tue May 16 14:11:25 CEST 2023
; jConfig Built on Tue Nov 26 09:26:22 CET 2019, Build Hash E3AA1574
;
; All Parameters declared in global modules
;

.equ SB_CLK_XILINX_CLKDV_DIVIDE                        , 2.0
.equ SB_CLK_XILINX_CLKDV_OUTPUT_FREQ                   , 1.35E7
.equ SB_CLK_XILINX_CLKFX_DIVIDE                        , 9
.equ SB_CLK_XILINX_CLKFX_MULTIPLY                      , 20
.equ SB_CLK_XILINX_CLKFX_OUTPUT_FREQ                   , 60000000
.equ SB_CLK_XILINX_CLKIN_DIVIDE_BY_2                   , 0
.equ SB_CLK_XILINX_CLKIN_DIVIDE_BY_2_DIVIDER           , 1
.equ SB_CLK_XILINX_DFS_FREQUENCY_MODE                  , "LOW"
.equ SB_CLK_XILINX_INSTANTIATE_BUFGFX                  , 0
.equ SB_CLK_XILINX_INSTANTIATE_BUFGS                   , 0
.equ SB_CLK_XILINX_INSTANTIATE_BUFGS2                  , 0
.equ SB_CLK_XILINX_RESET_LEVEL                         , "HIGH_ACTIVE"
.equ SB_SPARTANMC_BRKPT_TRAP                           , 1
.equ SB_SPARTANMC_CLOCK_GATING                         , 0
.equ SB_SPARTANMC_CODEMEM_CAN_STALL                    , 0
.equ SB_SPARTANMC_CODEMEM_CONNECTED                    , 1
.equ SB_SPARTANMC_COUNT_BREAKPOINTS                    , 4
.equ SB_SPARTANMC_COUNT_CYCLECOUNTERS                  , 1
.equ SB_SPARTANMC_COUNT_EVENTCOUNTERS                  , 2
.equ SB_SPARTANMC_COUNT_WATCHPOINTS                    , 4
.equ SB_SPARTANMC_DATAMEM_CAN_STALL                    , 0
.equ SB_SPARTANMC_DATAMEM_CONNECTED                    , 1
.equ SB_SPARTANMC_FORWARDING_CAN_STALL                 , 0
.equ SB_SPARTANMC_FREQUENCY                            , 60000000
.equ SB_SPARTANMC_HARDWARE_DEBUGGING                   , 0
.equ SB_SPARTANMC_HARDWARE_MUL                         , 1
.equ SB_SPARTANMC_IGNORE_UNCONNECTED                   , 0
.equ SB_SPARTANMC_INTR_VECTOR                          , 0x0
.equ SB_SPARTANMC_IO_BASE_ADR                          , 0x1fc00
.equ SB_SPARTANMC_IO_PREFIX                            , 0x7f
.equ SB_SPARTANMC_PERFORMANCE_COUNTER                  , 0
.equ SB_SPARTANMC_RESET_VECTOR                         , 0x0
.equ SB_SPARTANMC_SHOW_INSTR                           , 1
.equ SB_SPARTANMC_SINGLE_SHIFT                         , 0
.equ SB_SPARTANMC_SINGLE_STEP_TRAP                     , 3
.equ SB_SPARTANMC_STOP_SIM_ON_PERI_S9                  , 1
.equ SB_SPARTANMC_STOP_SIM_ON_X                        , 1
.equ SB_SPARTANMC_WIDTH_CYCLECOUNTER                   , 36
.equ SB_SPARTANMC_WIDTH_EVENTCOUNTER                   , 36
.equ SB_SPARTANMC_WTCHPT_TRAP                          , 2
