define JCONFIG_HDL_SOURCES
	/home/rs01/RS2/Versuch1/system/configuration.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/bus_address_verification/src/bus_address_verification_top.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/bus_address_verification/src/bus_address_verification_watcher.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/clocks/xilinx/clock_xilinx_dcm/src/clock.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/pselect.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/reg_access_decoder.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf_mem.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf_rptr_empty.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf_sync_r2w.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf_sync_w2r.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/common/src/yaf_wptr_full.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/alu.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/breakpoint_mgr.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/control.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/ex_mem.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/ifid.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/orgate.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/ormuxy.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/perfcounter.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/registerfile.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/spartanmc.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/specialfunction.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core/src/writeback.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/core_memory/src/spartanmc_mem_local.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/i2c_master/src/i2c_master_bit_ctrl.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/i2c_master/src/i2c_master_byte_ctrl.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/i2c_master/src/i2c_master_top.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/port_out/src/port_out.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/spi_master/src/spi.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/spmc_uart_light_peri.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_clk_gen.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_rx.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_rx_ctrl.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_rx_dp.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_tx.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_tx_ctrl.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/src/uart_light_tx_dp.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/bufgce_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/clk_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/clk_sys_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/ibufds_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/iddr2_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/iobuf_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/mult18_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/mux_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/obuft_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/oddr2_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/ram_18_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/ram_36_prim.v\
	/cad/spartanmc/rs2/19/spartanmc/hardware/vendor_prim/xilinx/ram_9_prim.v\

endef
export JCONFIG_HDL_SOURCES
