#
# Automatically generated by libJConfig-4.0-alpha0 @ rs2[fddccd3]
# Generated From: project.mk (/home/rs01/RS2/Versuch1/system/project.mk)
# Generated at Tue May 16 14:11:25 CEST 2023
# jConfig Built on Tue Nov 26 09:26:22 CET 2019, Build Hash E3AA1574
#
# Legacy Make-File, containing configuration for the make part of the toolchain
#

define JCONFIG_MODULES_ROOT
/cad/spartanmc/rs2/19/spartanmc/hardware
endef
export JCONFIG_MODULES_ROOT


define JCONFIG_MODULE_SRC_SUFFIX
/src/
endef
export JCONFIG_MODULE_SRC_SUFFIX


define JCONFIG_MODULE_IDS
clk_xilinx spartanmc spartanmc_i2c_master spartanmc_port_out spartanmc_spartanmc_mem_local spartanmc_spi_master spartanmc_uart_light
endef
export JCONFIG_MODULE_IDS


define JCONFIG_MODULE_DIRS
/cad/spartanmc/rs2/19/spartanmc/hardware/clocks/xilinx/clock_xilinx_dcm/. /cad/spartanmc/rs2/19/spartanmc/hardware/core/. /cad/spartanmc/rs2/19/spartanmc/hardware/i2c_master/. /cad/spartanmc/rs2/19/spartanmc/hardware/port_out/. /cad/spartanmc/rs2/19/spartanmc/hardware/core_memory/. /cad/spartanmc/rs2/19/spartanmc/hardware/spi_master/. /cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/.
endef
export JCONFIG_MODULE_DIRS


define JCONFIG_PATH_MAP
\
	path_clk_xilinx=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/clocks/xilinx/clock_xilinx_dcm/.] \
	path_spartanmc=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/core/.] \
	path_spartanmc_i2c_master=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/i2c_master/.] \
	path_spartanmc_port_out=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/port_out/.] \
	path_spartanmc_spartanmc_mem_local=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/core_memory/.] \
	path_spartanmc_spi_master=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/spi_master/.] \
	path_spartanmc_uart_light=Optional[/cad/spartanmc/rs2/19/spartanmc/hardware/uart_light/.]
endef
export JCONFIG_PATH_MAP


define JCONFIG_COREGEN_CONSTRAINTS
\

endef
export JCONFIG_COREGEN_CONSTRAINTS


define JCONFIG_COREGEN_CONSTRAINTS_MODIFIERS
(\
)
endef
export JCONFIG_COREGEN_CONSTRAINTS_MODIFIERS


define JCONFIG_TOP_MODULE
configuration
endef
export JCONFIG_TOP_MODULE


define JCONFIG_PRJNAME
spartanmc
endef
export JCONFIG_PRJNAME


define JCONFIG_CONSTRAINTS_FILE
/home/rs01/RS2/Versuch1/system/jconfig.ucf
endef
export JCONFIG_CONSTRAINTS_FILE


define JCONFIG_USR_CONSTRAINTS_FILE

endef
export JCONFIG_USR_CONSTRAINTS_FILE


define JCONFIG_VERSION
libJConfig-4.0-alpha0
endef
export JCONFIG_VERSION


define JCONFIG_SYSTEM_DIR
/home/rs01/RS2/Versuch1/system
endef
export JCONFIG_SYSTEM_DIR


define JCONFIG_HIERARCHY_PREFIX

endef
export JCONFIG_HIERARCHY_PREFIX


define JCONFIG_DEVICE
XC6SLX16-2CSG324
endef
export JCONFIG_DEVICE


define JCONFIG_FAMILY
Spartan-6
endef
export JCONFIG_FAMILY


define JCONFIG_TARGET
SP601
endef
export JCONFIG_TARGET


define JCONFIG_TARGET_PLATFORM
SP601\son\sXC6SLX16-2CSG324
endef
export JCONFIG_TARGET_PLATFORM


define JCONFIG_JTAGID
1
endef
export JCONFIG_JTAGID


define JCONFIG_TOOLCHAIN
ise
endef
export JCONFIG_TOOLCHAIN


define JCONFIG_OPT_PAR
-ol high -xe n
endef
export JCONFIG_OPT_PAR


define JCONFIG_OPT_BITGEN
-m -l
endef
export JCONFIG_OPT_BITGEN


define JCONFIG_OPT_SYNTHESIS
-p XC6SLX16-2CSG324 -ifmt mixed -ofmt NGC -opt_mode Speed -opt_level 1 -iuc NO -glob_opt ALLClockNets -rtlview YES -read_cores YES -write_timing_constraints NO -cross_clock_analysis NO -hierarchy_separator / -bus_delimiter [] -case maintain -slice_utilization_ratio 100 -fsm_extract YES -fsm_encoding Auto -fsm_style lut -ram_extract Yes -ram_style Auto -rom_extract Yes -rom_style Auto -shreg_extract YES -resource_sharing YES -mult_style auto -iobuf YES -max_fanout 500 -bufg 8 -register_duplication YES -equivalent_register_removal YES -register_balancing Yes -optimize_primitives No -iob auto -slice_utilization_ratio_maxmargin 5
endef
export JCONFIG_OPT_SYNTHESIS


define JCONFIG_OPT_NETGEN
-s 3
endef
export JCONFIG_OPT_NETGEN


define JCONFIG_OPT_PROGRAM

endef
export JCONFIG_OPT_PROGRAM


define JCONFIG_OPT_DEFINES

endef
export JCONFIG_OPT_DEFINES


define JCONFIG_OPT_MAP
-timing -p XC6SLX16-2CSG324 -logic_opt on -pr b -register_duplication -xe n -ol high
endef
export JCONFIG_OPT_MAP


define JCONFIG_OPT_TRANSLATE
-nt on -p XC6SLX16-2CSG324
endef
export JCONFIG_OPT_TRANSLATE


define JCONFIG_XML_FILE
/home/rs01/RS2/Versuch1/ourSpi.jc4
endef
export JCONFIG_XML_FILE


